//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessHishab
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyBazarList
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> UnitId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.Guid> PurchaserId { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
    
        public virtual Item tblItem { get; set; }
        public virtual Member tblMember { get; set; }
        public virtual Unit tblUnit { get; set; }
    }
}
