//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessHishab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Member tblMember { get; set; }
    }
}
