//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessHishab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.DailyBazarLists = new HashSet<DailyBazarList>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<System.Guid> UnitId { get; set; }
    
        public virtual ICollection<DailyBazarList> DailyBazarLists { get; set; }
        public virtual Category tblCategory { get; set; }
        public virtual Unit tblUnit { get; set; }
    }
}
