//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessHishab
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealChart
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Morning { get; set; }
        public Nullable<double> Midday { get; set; }
        public Nullable<double> Evening { get; set; }
        public Nullable<int> serialNo { get; set; }
    
        public virtual Member tblMember { get; set; }
    }
}
