//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessHishab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.DailyBazarLists = new HashSet<DailyBazarList>();
            this.Deposits = new HashSet<Deposit>();
            this.MealCharts = new HashSet<MealChart>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
    
        public virtual ICollection<DailyBazarList> DailyBazarLists { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual ICollection<MealChart> MealCharts { get; set; }
    }
}
