//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessHishab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.DailyBazarLists = new HashSet<DailyBazarList>();
            this.tblItems = new HashSet<Item>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DailyBazarList> DailyBazarLists { get; set; }
        public virtual ICollection<Item> tblItems { get; set; }
    }
}
